version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  todo:
    build:
      context: ./TodoService
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__TodoDb: "Server=db;Database=TodoDb;User Id=sa;Password=Your_password123;"
    ports:
      - "5000:80"
